server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans

spring:
  main:
    web-application-type=none:

freemarker:
  expose-request-attributes=true: