--IF OBJECT_ID('Seq1', 'SO') IS NOT NULL DROP SEQUENCE dbo.Seq1;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS JENRES;
DROP TABLE IF EXISTS BOOKS;

--CREATE SEQUENCE dbo.Seq1 AS INT START WITH 1 INCREMENT BY 1;
--CREATE SEQUENCE Seq1 START WITH 1 INCREMENT BY 1;
CREATE TABLE AUTHORS(AUTHORID BIGINT PRIMARY KEY AUTO_INCREMENT,
                     AUTHORNAME VARCHAR(50) NOT NULL,
                     LASTNAME VARCHAR(50) NOT NULL,
                     SURNAME VARCHAR(50));
CREATE TABLE JENRES(JENREID INT PRIMARY KEY AUTO_INCREMENT,
                     JENRE VARCHAR(25) NOT NULL);
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY AUTO_INCREMENT,
                     NAME VARCHAR(200) NOT NULL,
                     AUTHORID BIGINT,
                     JENREID INT,
                     YEAR VARCHAR(10),
                     FOREIGN KEY (AUTHORID)  REFERENCES AUTHORS (AUTHORID),
                     FOREIGN KEY (JENREID)  REFERENCES JENRES (JENREID));